services:
  - type: web
    name: socionet-api
    runtime: node
    rootDir: apps/api
    buildCommand: npm install
    startCommand: npx ts-node -r tsconfig-paths/register src/index.ts
    envVars:
      - key: NODE_ENV
        value: production